server:
  port: 8081
  address: 10.226.25.31

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  security:
    filter:
      order: 10

app:
  jwt:
    expiration-ms: 3600000
    refresh-expiration-ms: 86400000

logging:
  level:
    com.microservices.authservice: DEBUG
