server:
  port: 8081
  address: 10.226.25.31

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  jwt:
    expiration-ms: 3600000      # 60 minutes
    refresh-expiration-ms: 86400000  # 24 hours

# Service-specific logging
logging:
  level:
    com.microservices.authservice: DEBUG
    
# Security configuration
spring:
  security:
    filter:
      order: 10
