server:
  port: 8084
  address: 10.226.25.31

spring:
  application:
    name: git-service
  datasource:
    url: jdbc:mysql://localhost:3306/Git_service_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  
  security:
    filter:
      order: 10

# JWT configuration for git service (uses jwt.* structure)
jwt:
  secret: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ttsdashboard.com:8761/eureka
