spring:
 application:
   name: osticket-service
 autoconfigure:
   exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

superset:
 url: http://10.226.30.123:8088
 username: guest
 password: 12345

server:
 port: 8089
 address: 10.226.25.31 # Replace with a valid IP

eureka:
 instance:
   prefer-ip-address: true
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defaultZone: http://ttsdashboard.com:8761/eureka



jwt:
 secret: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
 expiration-ms: 3600000  # 60 minutes
 refresh-expiration-ms: 86400000  # 24 hours

